# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatingCompanyDataStepOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuarterOrAnnual', models.TextField(default='Annual')),
                ('AnnualFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedAnnual.csv')),
                ('QuarterFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedQuarterly.csv')),
                ('AnnualColumns', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns.csv')),
                ('QuarterColumns', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns_Quarterly.csv')),
                ('FileForTickers', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\TickerList.xlsx')),
                ('filepathfor_Excel', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
