# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_updatingcompanydatastepone_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatingcompanydatastepone',
            name='AnnualColumns',
        ),
        migrations.RemoveField(
            model_name='updatingcompanydatastepone',
            name='AnnualFile',
        ),
        migrations.RemoveField(
            model_name='updatingcompanydatastepone',
            name='FileForTickers',
        ),
        migrations.RemoveField(
            model_name='updatingcompanydatastepone',
            name='QuarterColumns',
        ),
        migrations.RemoveField(
            model_name='updatingcompanydatastepone',
            name='QuarterFile',
        ),
        migrations.RemoveField(
            model_name='updatingcompanydatastepone',
            name='filepathfor_Excel',
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='QuarterOrAnnual',
            field=models.TextField(default=''),
        ),
    ]
