# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_auto_20170204_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='AnnualColumns',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns.csv'),
        ),
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='AnnualFile',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedAnnual.csv'),
        ),
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='FileForTickers',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\TickerList.xlsx'),
        ),
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='QuarterColumns',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns_Quarterly.csv'),
        ),
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='QuarterFile',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedQuarterly.csv'),
        ),
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='filepathfor_Excel',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\'),
        ),
        migrations.AddField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 1, 6, 12, 502345, tzinfo=utc), verbose_name='date published'),
        ),
    ]
