# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_auto_20170204_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewDataPullFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TickersList', models.TextField(default='')),
                ('filepathfor_Excel', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\')),
                ('sector', models.TextField(default='new_tickers')),
                ('numperiods', models.IntegerField(default=12)),
                ('FileForColumns', models.TextField(default='"C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns.csv"')),
                ('QuarterOrAnnual', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 2, 52, 12, 789571, tzinfo=utc), verbose_name='date published'),
        ),
    ]
