# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_auto_20170206_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='FileForColumns',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns.csv'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 3, 4, 1, 158609, tzinfo=utc), verbose_name='date published'),
        ),
    ]
