# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_auto_20170207_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='QuarterOrAnnual',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly')], default='Annual', max_length=10),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 4, 30, 16, 445350, tzinfo=utc), verbose_name='date published'),
        ),
    ]
