# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0014_auto_20170208_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 2, 45, 44, 61877, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 2, 45, 44, 61377, tzinfo=utc), verbose_name='date published'),
        ),
    ]
