# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0016_auto_20170208_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeNewCompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedAnnual.csv')),
                ('QuarterFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedQuarterly.csv')),
                ('NewAnnualFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_new_tickersAnnual.xlsx')),
                ('NewQuarterFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_new_tickersQuarter.xlsx')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 2, 9, 4, 35, 44, 221968, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 4, 35, 44, 221467, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 4, 35, 44, 220967, tzinfo=utc), verbose_name='date published'),
        ),
    ]
