# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0017_auto_20170208_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewdatapullfile',
            old_name='FileForColumns',
            new_name='FileForColumnsAnnual',
        ),
        migrations.RemoveField(
            model_name='createnewdatapullfile',
            name='numperiods',
        ),
        migrations.AddField(
            model_name='createnewdatapullfile',
            name='FileForColumnsQuarter',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\Desired_BBG_Columns_Quarterly.csv'),
        ),
        migrations.AddField(
            model_name='createnewdatapullfile',
            name='numperiodsAnnual',
            field=models.IntegerField(default=10, help_text='Annual-10'),
        ),
        migrations.AddField(
            model_name='createnewdatapullfile',
            name='numperiodsQuarter',
            field=models.IntegerField(default=12, help_text='Quarterly-12'),
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 4, 58, 28, 530142, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='sector',
            field=models.TextField(default='new_tickers'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 4, 58, 28, 530643, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 4, 58, 28, 529642, tzinfo=utc), verbose_name='date published'),
        ),
    ]
