# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0018_auto_20170208_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerAndHistoricalChartsSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualFileLoc', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedAnnual.csv')),
                ('QuarterFileLoc', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedQuarterly.csv')),
                ('TickersFileLoc', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\TickerList.xlsx')),
                ('BaseSaveLoc', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\PeerGroups\\')),
                ('HistoricalChartBaseSaveLoc', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\PeerGroups\\CompanyData\\')),
                ('SectorOrIndustry', models.CharField(choices=[('Sector', True), ('Industry', False)], default='Sector', max_length=10)),
                ('IncludeLTMData', models.CharField(choices=[(True, True), (False, False)], default='Sector', max_length=10)),
                ('TickerExclusions', models.TextField(default='')),
                ('ChartColumns', models.TextField(default="'SALES_REV_TURN', 'SalesGrowth', 'BS_TOT_ASSET', 'TangibleAsset_Coverage', 'GC_ADJ_EBITDA', 'Adj_EBITDA_Margin', 'TotalLeverageAdj', 'NetLeverageAdj', 'EBITDA_to_Interest', 'CapEx_to_AdjEBITDA', 'ROA', 'UnleveragedFCFROA','EV_to_EBITDA_GC_Adj', 'Price_to_EPS_NTM', 'EQY_DVD_YLD_IND', 'CURRENT_TRR_1YR'")),
                ('HistoricalChartColumns', models.TextField(default="'SALES_REV_TURN', 'SalesGrowth', 'GC_ADJ_EBITDA', 'EBITDAGrowth', 'ROTA', 'UnleveragedFCFROTA', 'ROA', 'UnleveragedFCFROA', 'TangibleAsset_Coverage', 'Adj_EBITDA_Margin', 'Gross_Margin', 'TotalLeverageAdj', 'NetLeverageAdj', 'EBITDA_to_Interest', 'CapEx_to_AdjEBITDA'")),
                ('BaseSpreadSheetColumns', models.TextField(default="'Ticker', 'LATEST_PERIOD_END_DT_FULL_RECORD'")),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 20, 8, 17, 280840, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='NewQuarterFile',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_new_tickersQuarterly.xlsx'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 20, 8, 17, 281340, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 20, 8, 17, 280331, tzinfo=utc), verbose_name='date published'),
        ),
    ]
