# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0020_auto_20170211_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerandhistoricalchartssector',
            name='IndustryOptions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 0, 27, 59, 427084, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 0, 27, 59, 428085, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='peerandhistoricalchartssector',
            name='IncludeLTMData',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='peerandhistoricalchartssector',
            name='SectorOrIndustry',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='peerandhistoricalchartssector',
            name='TickerExclusions',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 0, 27, 59, 427084, tzinfo=utc), verbose_name='date published'),
        ),
    ]
