# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0021_auto_20170211_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 0, 29, 4, 836026, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 0, 29, 4, 836527, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='peerandhistoricalchartssector',
            name='IndustryOptions',
            field=models.CharField(choices=[('MetalsMining', 'MetalsMining'), ('TransportationInfrastructure', 'TransportationInfrastructure'), ('AutoComponents', 'AutoComponents')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 0, 29, 4, 835526, tzinfo=utc), verbose_name='date published'),
        ),
    ]
