# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0022_auto_20170211_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatingCompanyDataStepTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuarterOrAnnual', models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly')], default='Annual', max_length=10)),
                ('ExistingAnnualFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedAnnual.csv')),
                ('ExistingQuarterFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_CombinedQuarterly.csv')),
                ('NewAnnualFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_UpdateAnnual.csv')),
                ('NewQuarterFile', models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_UpdateQuarter.csv')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 2, 14, 3, 59, 54, 967878, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 14, 3, 59, 54, 968379, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 14, 3, 59, 54, 968379, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='peerandhistoricalchartssector',
            name='IndustryOptions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='peerandhistoricalchartssector',
            name='SectorOrIndustry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 14, 3, 59, 54, 967378, tzinfo=utc), verbose_name='date published'),
        ),
    ]
