# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0023_auto_20170213_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 2, 10, 526588, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='NewQuarterFile',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_new_tickersQuarter.xlsx'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 2, 10, 527088, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 2, 10, 525576, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='NewAnnualFile',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_UpdateAnnual.xlsx'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='NewQuarterFile',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\BloombergData\\BBG_UpdateQuarter.xlsx'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 2, 10, 526088, tzinfo=utc), verbose_name='date published'),
        ),
    ]
