# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0024_auto_20170221_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingClub_Initial_New_Origination_Data_Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileLocation', models.TextField(default='')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 27, 31, 498093, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 27, 31, 496592, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 27, 31, 497092, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 27, 31, 495591, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 4, 27, 31, 496092, tzinfo=utc), verbose_name='date published'),
        ),
    ]
