# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0032_auto_20170222_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            old_name='FileLocation',
            new_name='FileName',
        ),
        migrations.AddField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            name='BaseFileLocation',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\LendingClub\\'),
        ),
        migrations.AddField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            name='OutputFileLocation',
            field=models.TextField(default='C:\\Users\\gcole\\Documents\\LendingClub\\CleanedLCData\\'),
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 19, 54, 0, 802325, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 19, 54, 0, 803825, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 19, 54, 0, 802825, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 19, 54, 0, 801324, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 19, 54, 0, 801824, tzinfo=utc), verbose_name='date published'),
        ),
    ]
