# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0033_auto_20170311_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingClub_Combine_LC_App_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseFileDirectory', models.TextField(default='C:\\Users\\gcole\\Documents\\LendingClub\\CleanedLCData\\')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 20, 25, 34, 502467, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 20, 25, 34, 500979, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 20, 25, 34, 501980, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 20, 25, 34, 501479, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 20, 25, 34, 499983, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 20, 25, 34, 500484, tzinfo=utc), verbose_name='date published'),
        ),
    ]
