# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0037_auto_20170311_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingClub_ChargeOffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseFileDirectory', models.TextField(default='C:/Users/gcole/Documents/LendingClub/PaymentHistoryData/')),
                ('PaymentHistoryFile', models.TextField(default='C:/Users/gcole/Documents/LendingClub/PaymentHistoryData/PaymentHistoryData_Raw_Investor.csv')),
                ('MedianRecoveryRate', models.FloatField(default=0)),
                ('MeanRecoveryRate', models.FloatField(default=0)),
                ('RunTime', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 472629, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 469627, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_combine_lc_app_files',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 471629, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 471128, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 470128, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 469127, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 23, 17, 12, 469627, tzinfo=utc), verbose_name='date published'),
        ),
    ]
