# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0041_auto_20170311_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingClub_CleanCombinedApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationFileLocation', models.TextField(default='C:/Users/gcole/Documents/LendingClub/CleanedLCData/LCStatsAll.csv')),
                ('OutputFileLocation', models.TextField(default='C:/Users/gcole/Documents/LendingClub/CleanedLCData/LCStatsAll_Cleaned.csv')),
                ('WPSOutputFileLocation', models.TextField(default='C:/Users/gcole/Documents/LendingClub/CleanedLCData/LCStatsAll_WPS_Cleaned.csv')),
                ('RunTime', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 950955, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='createnewdatapullfile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 947453, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_chargeoffs',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 950455, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_combine_lc_app_files',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 949960, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lendingclub_initial_new_origination_data_cleaning',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 948954, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mergenewcompanydata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 947954, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatastepone',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 946453, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='updatingcompanydatasteptwo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 2, 38, 20, 946957, tzinfo=utc), verbose_name='date published'),
        ),
    ]
